Updated AppAdapter.java
NikLeberg/AdAid pull request #1
Opened 2022-06-28 20:33 UTC by TLGINO

Added function to filter displayed apps in AppAdapter.java in order to remove all system apps (as system apps tend to not contain ads).

2022-06-29 11:27 UTC, NikLeberg reviewed
Hi @TLGINO Thank you for your contribution!
Quite unexpected to have an open PR this fast to be honest. Are you actively using our app?
I agree that system apps don't have ads and your change would clean up the list quite a bit. I'll review it and maybe tweak the code formatting a little bit.

2022-07-16 09:58 UTC, NikLeberg requested changes
Hi @TLGINO
I redid the patch as review suggestions. Could you apply them please?

2022-07-16 09:58 UTC, NikLeberg commented on app/src/main/java/ch/bfh/adaid/gui/rule/AppAdapter.java
> + * @author Niklaus Leuenberger TLGINO
```suggestion
 * @author Niklaus Leuenberger, TLGINO
```

2022-07-16 09:58 UTC, NikLeberg commented on app/src/main/java/ch/bfh/adaid/gui/rule/AppAdapter.java
> +     * @return String[] of package names
```suggestion
     * Returns a list of names corresponding to the non-system file apps.
     *
     * @param packages List of found packages.
     * @return String[] Array of package names.
```

2022-07-16 09:58 UTC, NikLeberg commented on app/src/main/java/ch/bfh/adaid/gui/rule/AppAdapter.java
> +        return names.stream().toArray(String[]::new);
```suggestion
        return names.toArray(new String[0]);
```

2022-07-17 09:42 UTC, TLGINO commented
Looks good!

2022-07-17 10:03 UTC, NikLeberg approved these changes

2022-07-17 10:06 UTC, merged

2022-07-17 10:07 UTC, NikLeberg commented
Thanks!